'use client';
import { ArrowDownRight, Code2, Mail, Zap } from 'lucide-react';
import { useState } from 'react';

const projects = [
  {type:'Hardware',title:'Low-Power VLSI: CMOS vs. MGDIB',copy:'Transistor-level comparison using 0.35 µm technology: 27% fewer transistors, leakage reduced from 9.81 nA to 0.33 nA, and propagation delay reduced to 0.051 ns.',tags:['LTspice','CMOS','MGDIB']},
  {type:'AI / Software',title:'SkillSyncer — Resume Relevance System',copy:'LLM and vector-database assisted resume evaluation with FastAPI, NLP pipelines and automated decision support. National top-150 hackathon winner.',tags:['FastAPI','LLMs','ChromaDB']},
  {type:'AI / Software',title:'Yield Crop Prediction System',copy:'An XGBoost system estimating agricultural yield from weather and soil variables, awarded 2nd place at an inter-college hackathon.',tags:['XGBoost','Python','Data analysis']},
];

export default function Home() {
  const [filter,setFilter]=useState('All');
  return <main>
    <nav className="nav shell"><a className="brand" href="#top"><span>RK</span>Raushan Kumar</a><div className="navLinks"><a href="#work">Work</a><a href="#about">About</a><a className="navCta" href="mailto:raushankumar321670@gmail.com">Let&apos;s talk</a></div></nav>
    <section className="hero shell" id="top">
      <div className="heroCopy"><p className="eyebrow"><span className="pulse"/>Available for engineering opportunities · 2026</p><h1>Engineering intelligence,<br/><em>from silicon to systems.</em></h1><p className="lede">Electrical & Electronics engineer exploring low-power VLSI, power electronics and applied AI—turning physical insight into measurable, efficient systems.</p><div className="heroActions"><a className="primary" href="#work">Explore my work <ArrowDownRight size={18}/></a><a className="secondary" href="mailto:raushankumar321670@gmail.com"><Mail size={17}/> Get in touch</a></div></div>
      <div className="heroPanel" aria-label="Research performance highlights"><div className="panelTop"><span>Current research</span><Zap size={17}/></div><p className="panelTitle">Physics-guided optimization of a DC–DC buck converter</p><div className="metricGrid"><div><strong>70K</strong><span>design points</span></div><div><strong>0.964</strong><span>loss R²</span></div><div><strong>285</strong><span>LTspice runs</span></div><div><strong>100</strong><span>Pareto candidates</span></div></div><a href="https://github.com/rkmaurya93049/Physics-Guided-Multi-Fidelity-Residual-Learning-for-Multi-Objective-Design-of-a-DC-DC-Buck-Converter" target="_blank" rel="noreferrer">View research repository <Code2 size={16}/></a></div>
    </section>
    <section className="marquee"><div>VLSI DESIGN <i/> POWER ELECTRONICS <i/> EMBEDDED SYSTEMS <i/> APPLIED AI/ML <i/> CIRCUIT SIMULATION <i/> VERILOG <i/> VLSI DESIGN <i/> POWER ELECTRONICS</div></section>
    <section className="intro shell" id="about"><p className="sectionLabel">01 / Profile</p><h2>I work where <span>hardware constraints</span>, physical systems and intelligent software meet.</h2><p>My approach combines circuit-level analysis, real electrical infrastructure exposure and data-driven modeling. I care about work that is technically rigorous, testable and useful beyond the screen.</p></section>
    <section className="work shell" id="work"><div className="sectionHead"><div><p className="sectionLabel">02 / Selected work</p><h2>Projects with proof.</h2></div><a href="https://github.com/rkmaurya93049" target="_blank" rel="noreferrer">GitHub <ArrowDownRight size={17}/></a></div><article className="featured"><div className="projectNo">01</div><div><p className="projectType">Research · Power electronics · ML</p><h3>Physics-Guided Multi-Fidelity Residual Learning</h3><p>A simulation-level framework for multi-objective design of a fixed-duty 12 V-to-5 V buck converter, pairing analytical scale with validated switching simulations.</p><div className="tags"><span>LTspice</span><span>Python</span><span>NSGA-II</span><span>Residual learning</span></div></div><a aria-label="Open project" href="https://github.com/rkmaurya93049/Physics-Guided-Multi-Fidelity-Residual-Learning-for-Multi-Objective-Design-of-a-DC-DC-Buck-Converter" target="_blank" rel="noreferrer"><ArrowDownRight/></a></article>
      <div className="filters" aria-label="Filter projects">{['All','Hardware','AI / Software'].map(x=><button className={filter===x?'active':''} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div>
      <div className="projectGrid">{projects.filter(x=>filter==='All'||x.type===filter).map((p,i)=><article className="projectCard" key={p.title}><span>0{i+2}</span><p className="projectType">{p.type}</p><h3>{p.title}</h3><p>{p.copy}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div>
    </section>
    <section className="experience"><div className="shell"><p className="sectionLabel">03 / Field experience</p><div className="timeline"><article><span>2025—26</span><div><h3>Graduate Engineering Intern</h3><p>North Bihar Power Distribution Company Ltd.</p></div><p>33/11 kV substation operations, grid stability, transformers, load distribution and protection.</p></article><article><span>2025</span><div><h3>Electrical Engineering Intern</h3><p>Indian Railways</p></div><p>LHB coach electrical systems, RMPU, 750 V supply, DG sets and onboard power infrastructure.</p></article><article><span>2025</span><div><h3>AI & ML Intern</h3><p>Elevate Labs</p></div><p>Prediction pipelines, preprocessing, model training and evaluation. Recognized as Best Performer.</p></article><article><span>2023—24</span><div><h3>Salesforce Developer Program</h3><p>Salesforce</p></div><p>Cloud application development, Apex, Lightning Web Components, automation and API integration.</p></article></div></div></section>
    <section className="skills shell"><p className="sectionLabel">04 / Toolkit</p><div className="skillColumns"><div><h3>Electronics & VLSI</h3><p>CMOS design · Verilog RTL · LTspice · Digital electronics</p></div><div><h3>Power & Control</h3><p>Power systems · Control theory · Signal processing · Digital control</p></div><div><h3>Intelligent Systems</h3><p>Python · Scikit-learn · XGBoost · LLMs · LangChain</p></div><div><h3>Applications</h3><p>FastAPI · Streamlit · ChromaDB · SQL · C · C++</p></div></div></section>
    <section className="education shell"><div><p className="sectionLabel">05 / Education & recognition</p><h2>B.Tech in Electrical & Electronics Engineering</h2><p>Lok Nayak Jai Prakash Institute of Technology · 2022—2026 · CGPA 8.35/10</p></div><ul><li><strong>530</strong><span>Global rank · TCS CodeVita</span></li><li><strong>Top 150</strong><span>National hackathon · SkillSyncer</span></li><li><strong>2nd</strong><span>Inter-college hackathon · Yield prediction</span></li></ul></section>
    <footer><div className="shell"><p className="sectionLabel">Build something meaningful</p><h2>Let&apos;s turn engineering insight<br/>into <em>working systems.</em></h2><div className="footerLinks"><a href="mailto:raushankumar321670@gmail.com">raushankumar321670@gmail.com <ArrowDownRight/></a><a href="https://orcid.org/0009-0005-3755-1345" target="_blank" rel="noreferrer">ORCID</a><a href="https://github.com/rkmaurya93049" target="_blank" rel="noreferrer">GitHub</a></div><p className="fine">© 2026 Raushan Kumar · India</p></div></footer>
  </main>;
}

